sonar.projectKey=fiap-video-processor-api
sonar.organization=ivanzao
sonar.projectName=video-processor-api
sonar.sources=.
sonar.exclusions=**/*_test.go,**/testinfra/**,**/e2e/**,db/**,infra/**,web/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=cmd/**,**/testinfra/**,**/e2e/**
sonar.sourceEncoding=UTF-8
