- op: replace
  path: /spec/data/0/remoteRef/key
  value: video-processor/prod/worker/db-app
- op: replace
  path: /spec/data/1/remoteRef/key
  value: video-processor/prod/worker/mailersend
- op: replace
  path: /spec/data/2/remoteRef/key
  value: video-processor/prod/worker/mailersend
