apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: video-processor-prod

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
  - target:
      kind: ExternalSecret
      name: video-processor-worker
    path: externalsecret-patch.yaml
  - target:
      kind: ScaledObject
      name: video-processor-worker
    path: scaledobject-patch.yaml

images:
  - name: ghcr.io/ivanzao/video-processor-worker
    newTag: latest
