apiVersion: v1
kind: ConfigMap
metadata:
  name: video-processor-api-config
data:
  PORT: "8080"
  METRICS_PORT: "9090"
  AWS_REGION: us-east-1
  S3_BUCKET: set-by-overlay
  SNS_TOPIC_ARN: set-by-overlay
  SQS_QUEUE_URL: set-by-overlay
  OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy-gateway.observability.svc.cluster.local:4317
