apiVersion: batch/v1
kind: Job
metadata:
  name: video-processor-api-migrate
  labels:
    app: video-processor-api-migrate
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: video-processor-api-migrate
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: migrate
          image: ghcr.io/ivanzao/video-processor-api:latest
          args: ["migrate"]
          envFrom:
            - configMapRef:
                name: video-processor-api-config
            - secretRef:
                name: video-processor-api-secret
