apiVersion: v1
kind: ConfigMap
metadata:
  name: video-processor-api-config
data:
  S3_BUCKET: video-processor-prod-ACCOUNT_ID
  SNS_TOPIC_ARN: arn:aws:sns:us-east-1:ACCOUNT_ID:video-processor-api-events-prod
  SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/ACCOUNT_ID/video-processor-api-inbox-prod
