apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.storeName }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
  conditions:
    - namespaces:
{{- range .Values.namespaces }}
        - {{ . }}
{{- end }}
