apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: video-processor-worker
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: video-processor-worker-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: video-processor/set-by-overlay/worker/db-app
        property: url
    - secretKey: MAILERSEND_TOKEN
      remoteRef:
        key: video-processor/set-by-overlay/worker/mailersend
        property: token
    - secretKey: MAIL_FROM
      remoteRef:
        key: video-processor/set-by-overlay/worker/mailersend
        property: from
