apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: video-processor-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: video-processor-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: video-processor/set-by-overlay/auth/db-app
        property: url
