apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: video-processor-staging

resources:
  - ../../base

patches:
  - target:
      kind: ExternalSecret
      name: video-processor-auth
    path: externalsecret-patch.yaml

images:
  - name: ghcr.io/ivanzao/video-processor-auth-migrate
    newTag: latest
